package domain

import "errors"

var (
	ErrTokenInvalid                 = errors.New("Invalid token")
	ErrTokenExpired                 = errors.New("Token expired")
	ErrTokenNotFound                = errors.New("Token not found")
	ErrInvalidEmailOrPassword       = errors.New("Invalid email or password")
	ErrUserWithTheEmailAlreadyExist = errors.New("email already used")
	ErrUserWithThePhoneAlreadyExist = errors.New("phone already used")
	ErrUserNotFound                 = errors.New("user not found")
	ErrSessionNotFound              = errors.New("session not found")
	ErrSessionExpired               = errors.New("session expired")
	ErrVenueIDRequired              = errors.New("venue id is required for update")
	ErrVenueNotFound                = errors.New("venue not found")
	ErrVenueNotAvailableInTime      = errors.New("venue not available for requested time slot")
	ErrVenueNotApproved             = errors.New("venue is not approved for booking")
	ErrBookingFailed                = errors.New("venue booking failed for some reason")
	ErrBookingConflict              = errors.New(" booking conflicted with another booking: failed")
	ErrPaymentNotFound              = errors.New("payment not found")
	ErrPaymentNotCaptured           = errors.New("payment is not in captured state")
	ErrPaymentUpdateConflict        = errors.New("payment could not be updated due to current state")
	ErrPaymentAlreadyCaptured       = errors.New("payment has already been captured")
	ErrPaymentRefundFailed          = errors.New("payment refund update failed")
	ErrVenueMediaNotFound           = errors.New("venue media not found")
	ErrApplicationNotFound          = errors.New("application not found")
	ErrMediaUploadFailed            = errors.New("media upload failed")
	ErrMediaDeleteFailed            = errors.New("media delete failed")
	ErrIdempotencyConflict          = errors.New("idempotency key exists but is still pending")
)
